
services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-gestaoraul_db}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    networks:
      - app_network

  django_app:
    build:
      context: ./ 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/gestaoRaul/static
    environment:
      DEBUG: "False"
      ALLOWED_HOSTS: "rrbec.local.com, 0.0.0.0, django_app*"

    networks:
      - app_network

  nginx_server:
    build:
      context: ./NginxServer
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/gestaoRaul/static
    ports:
      - "80:80"
    depends_on:
      - django_app
    networks:
      - app_network

volumes:
  static_volume:
  db_data:

networks:
  app_network:
    driver: bridge