# Generated by Django 5.1.4 on 2024-12-10 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.CharField(blank=True, max_length=255, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandas.comanda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
