# Generated by Django 5.1.4 on 2024-12-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_productcomanda'),
        ('products', '0002_product_image_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='status',
            field=models.CharField(default='OPEN', max_length=255),
        ),
        migrations.AlterField(
            model_name='productcomanda',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
