# Generated by Django 5.1.4 on 2025-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cuisine',
            field=models.BooleanField(default=False),
        ),
    ]
